"""
dede_app.py — DeDe Course Builder Agent v2.0
Web interface for building Canvas IMSCC files from MeMe Blueprint documents.
Supports FULL BUILD and UPDATE modes.
"""

import streamlit as st
import io
import os
import sys
import traceback

# ── Page config ─────────────────────────────────────────────────
st.set_page_config(
    page_title="DeDe Course Builder",
    page_icon="🏗️",
    layout="centered",
)

# ── Import the build engine ─────────────────────────────────────
try:
    from build import (
        parse_blueprint,
        resolve_all_dates,
        validate_blueprint,
        build_imscc,
    )
    from style_templates import STYLES
except ImportError as e:
    st.error(f"Could not load build engine: {e}")
    st.stop()


# ── Styles (matches CeCe's theme) ──────────────────────────────
st.markdown("""
<style>
    .header-bar {
        background: linear-gradient(135deg, #2c3e50, #3498db);
        border-radius: 12px;
        padding: 2rem 2rem 1.5rem 2rem;
        margin-bottom: 1.5rem;
        text-align: center;
        color: white;
    }
    .header-bar h1 {
        font-size: 2.4rem;
        font-weight: 800;
        margin: 0;
        letter-spacing: -1px;
    }
    .header-bar p {
        margin: 0.3rem 0 0 0;
        opacity: 0.85;
        font-size: 1rem;
    }
    .stat-card {
        background: #f0f4ff;
        border: 1px solid #d0d8f0;
        border-radius: 10px;
        padding: 1rem;
        text-align: center;
    }
    .stat-number {
        font-size: 2rem;
        font-weight: 700;
        color: #2c3e50;
        line-height: 1;
    }
    .stat-label {
        font-size: 0.8rem;
        color: #666;
        margin-top: 4px;
    }
    .section-header {
        font-size: 0.85rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 1px;
        color: #888;
        margin: 1.5rem 0 0.5rem 0;
    }
    .badge-ok      { background:#d4edda; color:#155724; padding:3px 10px; border-radius:20px; font-size:0.85rem; font-weight:600; }
    .badge-warn    { background:#fff3cd; color:#856404; padding:3px 10px; border-radius:20px; font-size:0.85rem; font-weight:600; }
    .badge-error   { background:#f8d7da; color:#721c24; padding:3px 10px; border-radius:20px; font-size:0.85rem; font-weight:600; }
    .stDownloadButton > button {
        background: #2c3e50 !important;
        color: white !important;
        border: none !important;
        border-radius: 8px !important;
        font-weight: 600 !important;
        padding: 0.6rem 2rem !important;
        font-size: 1rem !important;
        width: 100%;
    }
    .stDownloadButton > button:hover {
        background: #3498db !important;
    }
    footer { visibility: hidden; }
    #MainMenu { visibility: hidden; }
</style>
""", unsafe_allow_html=True)


# ── Header ──────────────────────────────────────────────────────
st.markdown("""
<div class="header-bar">
    <h1>🏗️ DeDe</h1>
    <p>Course Builder Agent &nbsp;·&nbsp; Builds Canvas IMSCC from MeMe Blueprints</p>
</div>
""", unsafe_allow_html=True)


# ── Intro ────────────────────────────────────────────────────────
st.markdown("""
Upload the Blueprint document that MeMe produced and DeDe will build a 
Canvas-importable `.imscc` file. For **UPDATE mode**, also upload the 
original course export — DeDe will merge MeMe's changes while preserving 
untouched content.
""")


# ── Step 1: Blueprint ───────────────────────────────────────────
st.markdown('<p class="section-header">Step 1 — Upload the MeMe Blueprint</p>',
            unsafe_allow_html=True)

blueprint_file = st.file_uploader(
    label="Upload the Blueprint (.md) generated by MeMe",
    type=["md", "txt"],
    help="This is the filled Blueprint document from MeMe's consultation.",
    label_visibility="collapsed",
)

if blueprint_file is None:
    st.info("Upload a Blueprint `.md` file to get started.")
    st.stop()


# ── Step 2: Original IMSCC (optional for UPDATE mode) ──────────
st.markdown('<p class="section-header">Step 2 — Original course export (optional)</p>',
            unsafe_allow_html=True)

st.markdown(
    "For **UPDATE mode**, upload the original Canvas `.imscc` export. "
    "DeDe will merge Blueprint changes into it, preserving content that "
    "MeMe didn't change. Skip this for a **FULL BUILD** from scratch."
)

original_file = st.file_uploader(
    label="Upload original Canvas .imscc export (for UPDATE mode)",
    type=["imscc", "zip"],
    help="Optional. If provided, DeDe builds in UPDATE mode — merging changes into the original.",
    label_visibility="collapsed",
)


# ── Step 2.5: Style Selection ───────────────────────────────────
st.markdown('<p class="section-header">Design Style</p>',
            unsafe_allow_html=True)

st.markdown(
    "Choose a visual design template for homepage, module overview, and "
    "assignment pages. Select **No Styling** for plain Canvas HTML."
)

style_options = {v: k for k, v in STYLES.items()}
selected_style_label = st.selectbox(
    "Design style",
    options=list(style_options.keys()),
    index=0,
    label_visibility="collapsed",
)
selected_style = style_options[selected_style_label]

if selected_style != 'none':
    st.info(f"🎨 **{selected_style_label}** will be applied to homepage, module overview, and assignment pages.")


# ── Step 3: Parse & Validate ────────────────────────────────────
st.markdown('<p class="section-header">Step 3 — Build</p>',
            unsafe_allow_html=True)

build_button = st.button("🔨  Build Course", type="primary", use_container_width=True)

if not build_button and "last_build" not in st.session_state:
    st.stop()

# Cache key
bp_id = f"{blueprint_file.name}_{blueprint_file.size}"
orig_id = f"{original_file.name}_{original_file.size}" if original_file else "none"
cache_key = f"{bp_id}_{orig_id}_{selected_style}"

if build_button or st.session_state.get("last_build_key") != cache_key:

    with st.spinner("Parsing blueprint and building IMSCC..."):
        try:
            from io import StringIO
            import tempfile

            log_capture = StringIO()
            sys.stdout = log_capture

            # Read blueprint
            md_text = blueprint_file.read().decode("utf-8", errors="ignore")

            # Parse
            bp = parse_blueprint(md_text)

            # Validate
            warnings = validate_blueprint(bp)

            # Determine build mode
            build_mode = bp.get('build', {}).get('mode', 'FULL BUILD')
            if original_file:
                bp.setdefault('build', {})['mode'] = 'UPDATE'
                build_mode = 'UPDATE'

            # Build into temp file
            with tempfile.NamedTemporaryFile(suffix='.imscc', delete=False) as tmp:
                tmp_path = tmp.name

            # For UPDATE mode, write original IMSCC to a temp file too
            original_path = None
            if original_file and build_mode == 'UPDATE':
                orig_bytes = original_file.read()
                with tempfile.NamedTemporaryFile(suffix='.imscc', delete=False) as otmp:
                    otmp.write(orig_bytes)
                    original_path = otmp.name

            build_imscc(bp, tmp_path, original_imscc_path=original_path, style=selected_style)

            # Read built file into memory
            with open(tmp_path, 'rb') as f:
                built_bytes = f.read()

            # Clean up temp files
            os.unlink(tmp_path)
            if original_path:
                os.unlink(original_path)

            sys.stdout = sys.__stdout__
            log_output = log_capture.getvalue()

            # Cache result
            st.session_state["last_build"] = {
                "built_bytes":  built_bytes,
                "bp":           bp,
                "warnings":     warnings,
                "build_mode":   build_mode,
                "style":        selected_style,
                "log":          log_output,
                "bp_filename":  blueprint_file.name,
            }
            st.session_state["last_build_key"] = cache_key

        except Exception as e:
            sys.stdout = sys.__stdout__
            st.error(f"Build failed: {e}")
            with st.expander("Error details"):
                st.code(traceback.format_exc())
            st.stop()


# ── Display results ─────────────────────────────────────────────
result = st.session_state.get("last_build")
if not result:
    st.stop()

bp         = result["bp"]
warnings   = result["warnings"]
build_mode = result["build_mode"]

st.success(f"✅ Build complete! ({build_mode})")

st.markdown('<p class="section-header">Build Summary</p>', unsafe_allow_html=True)

# ── Course identity ──
course = bp.get("course", {})
title  = course.get("Course Title", "Unknown")
code   = course.get("Course Code", "Unknown")
st.markdown(f"### {title} — {code}")
start = course.get("Course Start Date", "Not set")
style_label = STYLES.get(result.get("style", "none"), "No Styling")
st.caption(f"Start: {start} · Mode: {build_mode} · Style: {style_label}")

# ── Stat cards ──
col1, col2, col3, col4, col5 = st.columns(5)
with col1:
    st.markdown(f'<div class="stat-card"><div class="stat-number">{len(bp.get("modules",[]))}</div>'
                f'<div class="stat-label">Modules</div></div>', unsafe_allow_html=True)
with col2:
    st.markdown(f'<div class="stat-card"><div class="stat-number">{len(bp.get("assignments",[]))}</div>'
                f'<div class="stat-label">Assignments</div></div>', unsafe_allow_html=True)
with col3:
    st.markdown(f'<div class="stat-card"><div class="stat-number">{len(bp.get("clos",[]))}</div>'
                f'<div class="stat-label">CLOs</div></div>', unsafe_allow_html=True)
with col4:
    st.markdown(f'<div class="stat-card"><div class="stat-number">{len(bp.get("grading",[]))}</div>'
                f'<div class="stat-label">Grade Groups</div></div>', unsafe_allow_html=True)
with col5:
    total_w = sum(g.get("weight", 0) for g in bp.get("grading", []))
    st.markdown(f'<div class="stat-card"><div class="stat-number">{total_w:.0f}%</div>'
                f'<div class="stat-label">Total Weight</div></div>', unsafe_allow_html=True)

st.markdown("")

# ── Warnings ──
if warnings:
    for w in warnings:
        st.warning(f"⚠️ {w}")
else:
    st.markdown('<span class="badge-ok">All validation checks passed</span>',
                unsafe_allow_html=True)

# ── Module detail ──
with st.expander(f"📦 Modules ({len(bp.get('modules',[]))})"):
    for mod in bp.get("modules", []):
        mlo_count = len(mod.get("mlos", []))
        assign_count = len(mod.get("assignments", []))
        st.markdown(f"**Module {mod.get('number','?')}: {mod.get('title','')}** "
                    f"— {mlo_count} MLOs, {assign_count} assignments")

with st.expander(f"📝 Assignments ({len(bp.get('assignments',[]))})"):
    for a in bp.get("assignments", []):
        pts = a.get("points", "?")
        grp = a.get("group", "?")
        st.markdown(f"**{a.get('title','')}** — {pts} pts, Group: {grp}")


# ── Download ─────────────────────────────────────────────────────
st.markdown('<p class="section-header">Step 4 — Download & Import</p>',
            unsafe_allow_html=True)

base_name     = os.path.splitext(result["bp_filename"])[0]
download_name = f"{base_name}_built.imscc"

built_kb = len(result["built_bytes"]) / 1024

st.download_button(
    label=f"⬇  Download IMSCC ({built_kb:.1f} KB)",
    data=result["built_bytes"],
    file_name=download_name,
    mime="application/zip",
    use_container_width=True,
)

st.markdown("""
**To import into Canvas:**
1. Open your course in Canvas
2. Go to **Settings** → **Import Course Content**
3. Select **Canvas Course Export Package** as the content type
4. Upload the `.imscc` file
5. Click **Import**
""")


# ── Build log ────────────────────────────────────────────────────
with st.expander("📋 Build log"):
    st.code(result["log"], language=None)


# ── Footer ──────────────────────────────────────────────────────
st.markdown("---")
st.caption(
    "DeDe Course Builder v2.0 · Part of the CeCe / MeMe / DeDe "
    "Instructional Design Suite · Developed for TOPkit / Florida SUS"
)
